#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

#define LED_ROT_ON		PORTA_OUTCLR = PIN4_bm
#define LED_ROT_OFF		PORTA_OUTSET = PIN4_bm
#define LED_ROT_TOGGLE	PORTA_OUTTGL = PIN4_bm
#define LED_GELB_ON		PORTA_OUTCLR = PIN5_bm
#define LED_GELB_OFF		PORTA_OUTSET = PIN5_bm
#define LED_GELB_TOGGLE	PORTA_OUTTGL = PIN5_bm
#define LED_GRUEN_ON		PORTA_OUTCLR = PIN6_bm
#define LED_GRUEN_OFF		PORTA_OUTSET = PIN6_bm
#define LED_GRUEN_TOGGLE	PORTA_OUTTGL = PIN6_bm
#define LED_BLAU_ON		PORTA_OUTCLR = PIN7_bm
#define LED_BLAU_OFF		PORTA_OUTSET = PIN7_bm
#define LED_BLAU_TOGGLE	PORTA_OUTTGL = PIN7_bm



#if BOARD == 1
/* LORA-AtXMega-Modul v01 */
#define LEDROT_PORT   PORTA
#define LEDROT_PIN    PIN4_bm
#define LEDGELB_PORT  PORTA
#define LEDGELB_PIN   PIN5_bm
#define LEDGRUEN_PORT PORTA
#define LEDGRUEN_PIN  PIN6_bm
#define LEDBLAU_PORT  PORTA
#define LEDBLAU_PIN   PIN7_bm
#elif BOARD == 2
/* ??? */
#endif // BOARD

#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN
#define LEDROT_TOGGLE  LEDROT_PORT.OUTTGL=LEDROT_PIN

#define LEDGRUENSETUP LEDGRUEN_PORT.DIRSET=LEDGRUEN_PIN
#define LEDGRUEN_ON   LEDGRUEN_PORT.OUTCLR=LEDGRUEN_PIN
#define LEDGRUEN_OFF  LEDGRUEN_PORT.OUTSET=LEDGRUEN_PIN
#define LEDGRUEN_TOGGLE  LEDGRUEN_PORT.OUTTGL=LEDGRUEN_PIN

#define LEDBLAUSETUP LEDBLAU_PORT.DIRSET=LEDBLAU_PIN
#define LEDBLAU_ON   LEDBLAU_PORT.OUTCLR=LEDBLAU_PIN
#define LEDBLAU_OFF  LEDBLAU_PORT.OUTSET=LEDBLAU_PIN
#define LEDBLAU_TOGGLE  LEDBLAU_PORT.OUTTGL=LEDBLAU_PIN

#endif // LEDHARDWARE_H_INCLUDED
